### PR TITLE
Drop Python 2.6 support

### PR DESCRIPTION
**Pull request by di**
Yesterday marks 3 years since the last release of Python 2.6! 🎉

To celebrate, I'm attempting to drop support for it from 156 prominent Python packages (one for every week it's past end-of-life)--including this one!

I've tried my best to remove as much 2.6-specific cruft as I can, but at the very least, this PR will remove the `'Programming Language :: Python :: 2.6'` trove classifier from this projects `setup.py`.

### CODE REVIEW

**Comment by dairiki** [comment]
Why drop python 2.6 support just for the sake of doing so?  (This PR removes exactly one instance of py26 cruft.)

**Comment by bertjwregeer** [comment]
@dairiki We no longer support Python 2.6 in Pyramid. In the next version of Pyramid Py2.6 becomes a hard error.

https://github.com/Pylons/pyramid/commit/a5c8100d780155643063742c716ac8d2f54e2e45

So it's actually a good idea from that standpoint that `pyramid_jinja2` support Py2.6 doesn't really gain you anything unless you want to continue running older versions of Pyramid.

Also, it will become more difficult to test `pyramid_jinja2` once `pyramid` becomes un-installable on Py2.6.

**Comment by di** [comment]
For this project, a good reason might be because Pyramid no longer supports Python 2.6 either: https://github.com/Pylons/pyramid/pull/2759

However, you're right, there's not much to this PR.

**Comment by dairiki** [comment]
Valid points, those...

But Pyramid 1.6 supports py26, and is still actively maintained (afaik.)
Why cause trouble for that small subset of users who are stuck with python 2.6?

I think the right time to drop py26 support is at the point where maintaining support starts to cause pain (e.g. difficulty testing), not in anticipation of that pain...  (It's easy enough to drop, once that time comes.)

**Comment by bertjwregeer** [comment]
We dropped Py2.6 support in Pyramid because it is past EOL not because it was a pain to maintain or difficult to test.

We've been dropping it across all of the various projects. As core devs get time to touch various addons we remove Py2.6 support.

Keeping it around in `pyramid_jinja2` makes it a special snowflake.

Also, with a bit of luck Pyramid 1.8 is almost around the corner, which drops support for Pyramid 1.6.

**Comment by mmerickel** [comment]
If we dropped support for Python 2.6 in Pyramid then it becomes a pain in pyramid_jinja2 because either 1) we stop testing it on newest pyramid on 2.6 or 2) ???.  This is the definition of a burden.

Pyramid dropped 2.6 because it is actively using certain features that are only 2.7+ such as set comprehensions and `{}` syntax in strings. This is the decision we've made and if anyone wants to keep using 2.6 then they need to use older versions of the bindings. They are free to keep using newer pyramid_jinja2 versions of course, but with no guarantee that they have been testing to work on 2.6.

**Comment by mmerickel** [comment]
Thanks @di!

**Pull request merged**
