### PR TITLE
Fixed a typo in template.

### PR DESCRIPTION
**Pull request by navinkarkera**
Now changing locale to fr or de will work.
Hello! -> Bonjour!
Hello! -> Halo!

### CODE REVIEW

**Comment by navinkarkera** [comment]
Fix for issue no #125

**Comment by stevepiercy** [comment]
I'd suggest that this scaffold be made consistent with the [Pyramid starter scaffold](https://github.com/stevepiercy/pyramid/blob/master/pyramid/scaffolds/starter/%2Bpackage%2B/templates/mytemplate.pt_tmpl#L37). There should be no `!`. The phrase "Hello to 'project name'" is awkward and clumsy in English. "Welcome to", "Willkommen zum", and "Bienvenue au" are more correct.

Side note, I only know these phrases because I performed in a local summer theatre production of Cabaret during high school. I knew that would be useful some day! 😛

**Comment by navinkarkera** [comment]
I'll change the "Hello!" phrase to "Welcome to".

**Comment by stevepiercy** [comment]
Closing in favor of #138

**Comment by stevepiercy** [comment]
@navinkarkera sorry, we both jumped at this at the same time.

It was not the "!" causing the problem, but insufficient documentation. I've updated it accordingly, as well as a few related updates to bring the scaffolds up to date with Pyramid core.
http://docs.pylonsproject.org/projects/pyramid_jinja2/en/latest/#pcreate-template-i18n

**Pull request closed without merging**
